### ISSUE TITLE
MAPQ correction implementation

### ISSUE THREAD

**Issue by kopardev** [RBL-NCI/iCLIP#73] opened 2021-05-06 17:02 UTC
1. Align reads 3 ways
   * To genome (splice unaware)
   * To exon masked genome + transcriptome (splice aware 1)
   * To genome + transcriptome (splice aware 2)
2. deduplicate "splice aware 2" BAM file
3. generated readid list from deduplicated "splice aware 2" BAM file
4. Subsample "splice unaware" BAM and "splice aware 1" BAM files using the readids from 3.
5. Input deduplicate "splice aware 2" BAM file and the 2 BAMs from 4. to my pysam script for MAPQ correction
6. BAM file generated from 5. if the file for visualization!

**Comment by slsevilla** [comment] 2021-05-06 17:19
**currently this is the workflow with each (-) indicating a separate rule:**
- alignment (A)
- cleanup (A)
- genomic coordinates (A)
- split unique and mm (A)
- merge unique / mm into BAM (A)
- run QC on BAM (A)
- deduplicate (A)
- perform counts (A)

**the new workflow (with ** indicating a new or updated rule) for both unmapped and updated alignment would be:**
- **alignment 3 ways - A) "splice unaware" B) "splice aware 1" C) "splice aware 2"
- cleanup of (C)
- genomic coordinates conversion of (C)
- **merge unmapped reads back into genomic coordinates conversion of (C) - will handle issue #58 
- split unique and mm of (C)
- merge unique / mm into BAM of (C)
- run QC on BAMof (C)
- deduplicate of (C)
- **generate readid list (C)
- **subsample "A) splice unaware" BAM and "B) splice aware 1" BAM files using the readids from (C)
- **input deduplicate (C) BAM file and the 2 BAMs subset A) and subset B) pysam script for MAPQ correction - outputs D) updated mapq score bam file
- **Use D) for visualization with stats on % of reads with MAPQ score changes
- perform counts on (D)

**Comment by slsevilla** [comment] 2021-06-08 20:13
@kopardev i'm running into a key error with the readids python script you wrote for iCLIP.

i'm running this command:
```
python /home/sevillas2/git/iCLIP/workflow/scripts/06_filter_bam_by_readids.py \
--inputBAM /scratch/sevillas2/phil_test/09_dedup/01_bam/Ro_Clip.unaware.dedup.bam \
--outputBAM /scratch/sevillas2/phil_test/10_mapq_score/Ro_Clip.unaware_subset.bam \
--readids /scratch/sevillas2/phil_test/10_mapq_score/Ro_Clip.readids.txt;
```


and the error is: 
```
Traceback (most recent call last):

  File "/home/sevillas2/git/iCLIP/workflow/scripts/06_filter_bam_by_readids.py", line 32, in <module>

    for read in bigdict[r]:

KeyError: 'M02511:198:000000000-J3HNN:1:1101:10900:1318:rbc:AACAGAGTC'
```

All output files are located within my scratch folder /scratch/sevillas2/phil_test/. Can you take a look for me? I'm not sure what the problem is here...

**Comment by slsevilla** [comment] 2021-06-08 23:38
Part of the problem was that both unaware (splice unaware) and masked (splice aware 1) input files were being deduplicated prior to entering the subsampling step. This has been fixed and spliced unaware was able to complete subsampling.

The problem has not resolved with the masked (splice aware 1) file, however. This file is still resulting in an error where reads are missing:
`python /home/sevillas2/git/iCLIP/workflow/scripts/06_filter_bam_by_readids.py \
--inputBAM /scratch/sevillas2/phil_test/08_bam_merged/Ro_Clip.masked.merged.si.bam \
--outputBAM /scratch/sevillas2/phil_test/10_mapq_score/Ro_Clip.masked.subset.bam \
--readids /scratch/sevillas2/phil_test/10_mapq_score/Ro_Clip.readids.txt`

Results in this error:
```
Traceback (most recent call last):
  File "/home/sevillas2/git/iCLIP/workflow/scripts/06_filter_bam_by_readids.py", line 32, in <module>
    for read in bigdict[r]:
KeyError: 'M02511:198:000000000-J3HNN:1:1101:10129:1351:rbc:ATAAAAAGA'
```

Reviewing the input file confirms that this read is not present, although it is present in the unmasked (splice aware 2) file where readids were generated:
```
samtools view /scratch/sevillas2/phil_test/08_bam_merged/Ro_Clip.masked.merged.si.bam|grep "10129:1351"|wc -l
0

samtools view /scratch/sevillas2/phil_test/09_dedup/01_bam/Ro_Clip.unmasked.dedup.bam|grep "10129:1351"|wc -l
1
```

**Comment by kopardev** [comment] 2021-06-09 12:39
This is strange. Can you confirm that this readid is present in the input fastqs that go into "splice aware 1" alignment? Ideally, input fastq files should be the same for all 3 alignments.

**Comment by slsevilla** [comment] 2022-05-16 19:41
Process complete and integrated in [v1.1](https://github.com/RBL-NCI/iCLIP/releases/tag/v1.1)

**Closed by slsevilla** 2022-05-16 19:41 UTC
Labels: enhancement
